/* BASICS */
export const HANDLE_ERROR = 'HANDLE_ERROR';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
/* INITIAL */
export const GET_PAGINATED_POKEMONS = 'GET_PAGINATED_POKEMONS';
/* UPDATE POKEMONS */
export const CHANGE_ALL_POKEMONS = 'CHANGE_ALL_POKEMONS';
export const CHANGE_CURRENT_POKEMONS = 'CHANGE_CURRENT_POKEMONS';
/* SORTS */
export const SORT_BY_ID = 'SORT_BY_ID';
export const SORT_BY_NAME_ASC = 'SORT_BY_NAME_ASC';
export const SORT_BY_NAME_DESC = 'SORT_BY_NAME_DESC';
export const SORT_BY_POINTS = 'SORT_BY_POINTS';
/* POKEMON DETAIL */
export const GET_POKEMON_BY_ID_NAME = 'GET_POKEMON_BY_ID_NAME';
